[package]
name = "hyper-sync-rustls"
version = "0.3.0-rc.4"
authors = ["Sergio Benitez <sb@sergio.bz>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Glue code for Rustls and synchronous Hyper."
homepage = "https://github.com/SergioBenitez/hyper-sync-rustls"
repository = "https://github.com/SergioBenitez/hyper-sync-rustls"

[features]
default = ["client", "server"]
client = ["webpki-roots", "webpki"]
server = []

[dependencies]
webpki-roots = { version = "0.15", optional = true }
webpki = { version = "0.18", optional = true }
rustls = "0.14"

[patch.crates-io]
rustls = { git = 'https://github.com/blaggacao/rustls', branch = "da-implement-ecdsa-keys" }

[dependencies.hyper]
version = "0.10"
default-features = false

[dev-dependencies]
